### ISSUE TITLE
Confusing homepage statement. Is drawbridge obsolete?

### ISSUE THREAD

**Issue by AlexAti** [cemerick/drawbridge#19]
Hi cemerick,

The front page states: "Drawbridge is compatible with Clojure 1.2.0 - 1.4.0." (and 1.4 is from 2012)

Whereas I see commits reaching 2015, and Heroku has documentation from February 2016 helping to set drawbridge up in a new project (https://devcenter.heroku.com/articles/debugging-clojure).

Is that really true?

It would be good to either take that comment off, or state more boldly that this is an obsolete project, as I assume I won't be the only one which is confused. For example in this discussion (about an issue that I share) that specific line was quoted: http://stackoverflow.com/questions/20088908/problems-connecting-to-a-clojure-nrepl-with-ring-compojure

In any case, thanks for sharing your work!

**Comment by theronic** [comment]
Would still love to use Drawbridge to talk to my Clojure 1.8 REPL on Heroku :)

**Comment by cemerick** [comment]
I shouldn't have put such a precise range there. I'll update the readme to be open-ended.
